name: flag_domain
description: Modelos de dominio (DTOs) compartilhados entre os apps do Flag Platform.
version: 0.3.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
